name       : kodi-platform
version    : 59  # git rev-list --count 915da08 (2019-04-29)
release    : 3
source     :
    - git|https://github.com/xbmc/kodi-platform.git : 915da086fa7b4ea72796052a04ed6de95501b95c 
license    : GPL-2.0-or-later
component  : desktop.multimedia
summary    : Kodi platform support library
description: |
    Kodi binary add-ons depend on the Kodi platform support library.
builddeps  :
    - kodi-devel
    - pkgconfig(p8-platform)
    - pkgconfig(tinyxml)
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
